# Generated by Django 3.0.6 on 2020-08-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelrepair', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
