# Generated by Django 3.0.6 on 2020-08-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ee_name', models.CharField(max_length=30)),
                ('ee_rollnumber', models.CharField(max_length=10)),
                ('ee_year', models.CharField(max_length=15)),
                ('ee_branch', models.CharField(max_length=2)),
                ('ee_reason', models.CharField(default='None', max_length=100)),
                ('ee_start_date', models.DateField()),
                ('ee_end_date', models.DateField()),
                ('ee_applydate', models.DateField(auto_now=True)),
                ('ee_permission', models.CharField(max_length=10)),
            ],
        ),
    ]
