# Generated by Django 3.0.6 on 2020-08-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messfeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(max_length=20)),
                ('rating', models.SmallIntegerField()),
                ('review', models.TextField(max_length=300)),
            ],
        ),
    ]
