# Generated by Django 3.0.6 on 2020-08-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labrepair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.CharField(max_length=10)),
                ('system', models.IntegerField()),
                ('problem', models.CharField(max_length=15)),
            ],
        ),
    ]
