# Generated by Django 3.0.6 on 2020-08-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrepair',
            name='lab_status',
            field=models.CharField(default='none', max_length=15),
        ),
    ]
