# Generated by Django 3.0.6 on 2020-08-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_name', models.CharField(max_length=30)),
                ('it_rollnumber', models.CharField(max_length=10)),
                ('it_year', models.CharField(max_length=15)),
                ('it_branch', models.CharField(max_length=2)),
                ('it_start_date', models.DateField()),
                ('it_end_date', models.DateField()),
                ('it_applydate', models.DateField(auto_now=True)),
                ('it_permission', models.CharField(max_length=10)),
            ],
        ),
    ]
