# Generated by Django 3.0.6 on 2020-08-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpassIT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='it',
            name='it_reason',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
